### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dmrlawson** [attzonko/mmpy_bot#129]
Hi,

I just moved our irc bot to this and it was very painless, thanks!

Would you consider pushing a new release to pypi? There have been some useful commits since the last one.

Many thanks,

David

**Comment by attzonko** [comment]
My dev environment for this has been on hiatus for a while. I will try and get it back up to do this. I would like to re-enable Travis CI to make sure all the code is still passing the automated CI, as a few commits were merged without it. 

How urgent is this for you?

**Comment by dmrlawson** [comment]
Not urgent, we can always install from git.

Anything I can do to help?

**Comment by rwky** [comment]
Looking at the travis failures it's because they connect to mmpy-bot.duckdns.org which isn't responding.

From your comment above I assume this means that it's a mattermost instance running on your personal network.

What could be done is to run [mattermost via docker](https://github.com/mattermost/mattermost-docker) in the `before_install` section and connect to that instead, the hard part would be boostrapping mattermost

**Comment by dmrlawson** [comment]
There's a one-liner in the documentation: https://docs.mattermost.com/install/docker-local-machine.html#one-line-docker-install

I don't have experience of configuring travis, but I might give it a go

**Comment by rwky** [comment]
Oh nice! I might give that a go myself if I can find time :)

**Comment by rwky** [comment]
I've had a chance to look at this and made a PR #150

The behaviour tests only required minor changes and I've added a script to allow people to run tests in docker locally.

Hopefully this means we can get a new release out :)

**Comment by attzonko** [comment]
OK release done 😌
