### ISSUE TITLE
Triggering a "Interactive Button" using another

### ISSUE THREAD

**Issue by sanket189** [attzonko/mmpy_bot#159]
Hi Team - I'm right now in need of "Responding" to an "Interactive Button" with another message with a List-of-Interactive buttons, following is the control flow:

Getting Request options (Interactive Button) -> Getting Request Type (Interactive button) -> Mattermost Dialog. 

Is this feasible? Please advise.

NOTE: I tried triggering Nested Interactive-Dialog, but it didn't work (as trigger-id was expiring). Please advise.

**Comment by jneeven** [comment]
Yes, I don't see why not; you could probably respond with another interactive form [here](https://github.com/attzonko/mmpy_bot/blob/master/mmpy_bot/plugins/webhook_example.py#L22) instead of text. The `props` argument is set to `{}` there, but you can probably update it with another interactive form attachment.

**Comment by jneeven** [comment]
I'm closing this issue, but let me know if it doesn't work!
