### ISSUE TITLE
Is click.group supported?

### ISSUE THREAD

**Issue by lweddewer** [attzonko/mmpy_bot#196]
Have played around with mmpy_bot version 2.0 and click a little bit. 
Tryed to use click.group to use the full power of this library.
I found now way to make it work.
Is this feature supported with mmpy_bot.
If yes can one provide an example?

Regards

**Comment by jneeven** [comment]
Hi! I haven't tested that yet, so I'm not sure to what extent it works or what changes might be needed. What problems are you running into if you try this?

**Comment by lweddewer** [comment]
Following the click discription I tryed to use the subcommand feature:

```python
@listen_to('main')
@click.group()
def main():
    pass

#@listen_to('subcommand')
@main.command()
def subcommand():
    click.echo('do subcommand')

```

But always get:
```    
@main.command()
AttributeError: 'MessageFunction' object has no attribute 'command'
```

Regrads

**Comment by jneeven** [comment]
Okay, that makes sense. The `@listen_to('main')` turns `main()` from a click group into a `MessageFunction`, so then you cannot register any subcommands to it. I think you can easily work around this (although it isn't very pretty) by using `listen_to` in the following way (which we actually do in the [base Plugin class](https://github.com/attzonko/mmpy_bot/blob/master/mmpy_bot/plugins/base.py#L38)):

```python
def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    # Wrap self.main in a MessageFunction
    self.main = listen_to("main")(self.main)

@click.group()
def main():
    pass

@listen_to('subcommand')
@main.command()
def subcommand(self):
    click.echo('do subcommand')
 ```

However, I suspect this still won't work because `@main.command()` will try to find a variable `main`, and there is none (it will be `self.main`). I'd still give it a try though! Maybe you can find a workaround for that as well.

If we'd want to improve support for this, we'd have to add a bunch of complexity to the `Function` class. We [currently just loop over all attributes of the Plugin and check if any of them are `Function`s](https://github.com/attzonko/mmpy_bot/blob/master/mmpy_bot/plugins/base.py#L43), which won't be the case if you wrap them in `click` groups or commands. The alternative would be to, in the `__init__` of the `Function` class, find the calling class to see which plugin defined it. It's not impossible, but not very pretty either.

**Comment by attzonko** [comment]
I am closing this as there has not been any follow up for a long time. The answer to the question is that currently click groups are not supported.
