### ISSUE TITLE
Issue with Websockets on 6.4.x

### ISSUE THREAD

**Issue by cs2000** [attzonko/mmpy_bot#291]
**Describe the bug**
Im currently running MM version 6.2.1 using MMPY_Bot's latest release, this has been working just fine for a while. AFter completing an upgrade to MM version 6.4.x, the bot can no longer fully connect to the server. It posts a message in a pre-defined channel saying it is online, but seems to no longer be listening for trigger words.

**How To Reproduce**
It may be related to my instance only, but install the latest version of both MMPY_Bot and Mattermost and test

**Expected behavior**
The bot should listen and respond to commands as before

**Operating Environment (please complete the following information):**
-Mattermost version 6.4.1 or 6.4.0
-MMPY_Bot version 2.0.2
-Ubuntu 20.04.3 LTS

Attaches is a SSH capture of the error.
![Capture](https://user-images.githubusercontent.com/6414386/155825901-df1463ee-cc84-4517-ba15-403aa2afceb6.PNG)

Nothing has changed (of note) in mt bot or MM config files. I could be making a stupid mistake of course, but thought id ask the question as i really would like to be running the latest mattermost release for security reasons.

**Comment by attzonko** [comment]
Thanks for reporting this issue. Can you let us know what version of the MM driver you have installed?

**Comment by cs2000** [comment]
So yeah, this now works, i totally forgot about mattermostdriver and it did not auto-upgrade with the script im using to handle to upgrade of the core MM component.

Issued `pip install mattermostdriver -U` and then did the upgrade of MM. Put my bot files back onto the server and restarted the bot's service and all is now good.

Maybe out of scope, but a way for the bot to check if mattermostdriver compatible with the installed version of MM would be a good idea, but can be un-labeled as a bug!

**Comment by attzonko** [comment]
I am open for suggestions on what the logic could be to check the "MM Driver" version against the running "MM" version. I think if the driver had an API that would provide the information, we could use it, but as far as I know there is no way to do that today.  Someone would need to maintain a mapping of "compatible" versions. In theory a CI system could do that, but I don't think anyone will go that heavy for this.

You are very welcome. I did not write it originally, I was just a heavy user a while back, and ended up taking over when the original developer went MIA. It has since been re-written to modernize it and use asyncio (v2+), again not by me, but I try and remain active for the sake of the package. Enjoy!
