### ISSUE TITLE
Need to fix get_username()

### ISSUE THREAD

**Issue by attzonko** [attzonko/mmpy_bot#30]
Message.get_username() without a parameter should return the Message's sender username, the current behavior is returning the username for the owner of the web-hook.  The difference is in _body['data']['post']['user_id'] vs _body['data'].get('sender_name', '').strip()

**Comment by seLain** [comment]
There is a chance that ``username(user_id) != sender_name`` .

When sending post through webhook, there is a parameter ``username`` which can [overrides the username the message posts as](https://developers.mattermost.com/integrate/incoming-webhooks/) if [``EnablePostUsernameOverride``](https://docs.mattermost.com/administration/config-settings.html#enable-integrations-to-override-usernames) is set to ``true``.

### Example 1 : EnablePostUsernameOverride = false

For example, if we send a hello post through webhook with ``username = "mockname"`` when ``EnablePostUsernameOverride = false`` (default), the post will look like this : 

{'event': 'posted', 'data': {'channel_display_name': 'Off-Topic', 'channel_name': 'off-topic', 'channel_type': 'O', 'post': {'id': 'hu8s8abo3fy69xt7nwfm1fq3ka', 'create_at': 1531852142221, 'update_at': 1531852142221, 'edit_at': 0, 'delete_at': 0, 'is_pinned': False, **'user_id': 'ta7a1ceamt8kiegt445emo6e5h'**, 'channel_id': '4fgt3n51f7ftpff91gk1iy1zow', 'root_id': '', 'parent_id': '', 'original_id': '', 'message': 'hello', 'type': '', 'props': {**'from_webhook': 'true'**}, 'hashtags': '', 'pending_post_id': ''}, **'sender_name': 'amy'**, 'team_id': 'au64gza3iint3r31e7ewbrrasw'}, 'broadcast': {'omit_users': None, 'user_id': '', 'channel_id': '4fgt3n51f7ftpff91gk1iy1zow', 'team_id': ''}, 'seq': 2, 'message_type': '?'}

The name displayed on MM channel will be **amy [bot]**.

### Example 2 : EnablePostUsernameOverride = true

And if it is sent when ``EnablePostUsernameOverride = true``, the post will be : 

{'event': 'posted', 'data': {'channel_display_name': 'Off-Topic', 'channel_name': 'off-topic', 'channel_type': 'O', 'post': {'id': '45o6whbrp3no5djmg5iabm14ky', 'create_at': 1531879612382, 'update_at': 1531879612382, 'edit_at': 0, 'delete_at': 0, 'is_pinned': False, **'user_id': 'ta7a1ceamt8kiegt445emo6e5h'**, 'channel_id': '4fgt3n51f7ftpff91gk1iy1zow', 'root_id': '', 'parent_id': '', 'original_id': '', 'message': 'hello', 'type': '', 'props': {**'from_webhook': 'true'**, **'override_username': 'mockname'**}, 'hashtags': '', 'pending_post_id': ''}, **'sender_name': 'mockname'**, 'team_id': 'au64gza3iint3r31e7ewbrrasw'}, 'broadcast': {'omit_users': None, 'user_id': '', 'channel_id': '4fgt3n51f7ftpff91gk1iy1zow', 'team_id': ''}, 'seq': 2, 'message_type': '?'}

The name displayed on MM channel will be **mockname [bot]**.

### Diff

Both posts are sent by the same user account, so the ``user_id`` is also the same. But example2 has ``sender_name`` overridden, and an additional ``override_username``.

So I think the current code is fine since it returns the actual username by user_id.
```
def get_username(self, user_id=None):
    return self.get_user_info('username', user_id)
```
If developers need to get **sender_name** or **override_username**, maybe we should consider expose them as public methods ?

**Comment by attzonko** [comment]
When the user_id paramter is provided to Message.get_username(user_id) I totally agree with you we should lookup the username by the user_id. However, we should try to think about the intent of calling Message.get_username() when no parameter is given. In that case in my opinion the most logical intent seems to be to get the username seen in the channel for that message, regardless of the fact that it could be overridden. Does that make sense @seLain?

We could expose both **sender_name** and **override_username** if you think those are also needed.

**Comment by seLain** [comment]
Well, I just thought originally `get_username` would return the actual username. So I tried to make clear if `username(user_id) != sender_name` in some cases. 

If the intention is to get the username seen in the channel for that message when user_id is given none, I am ok with the change :)

**Comment by attzonko** [comment]
Well originally, before I made the changes, the code always just returned the sender name regardless of user_id given or not. So I will go ahead and merge the change in to at least restore the way it worked when user_id is None. Thanks for digging into the details of how the username override stuff actually works.

**Comment by at4446** [comment]
@attzonko I am trying to use get_user_info(USER_ID) but I want it to get the USER_ID dynamically. is there any method to use for this purpose? basically I cannot hard code the USER_ID and I want the script to pull out the user ID of the person talking to the BOT.

**Comment by attzonko** [comment]
> @attzonko I am trying to use get_user_info(USER_ID) but I want it to get the USER_ID dynamically. is there any method to use for this purpose? basically I cannot hard code the USER_ID and I want the script to pull out the user ID of the person talking to the BOT.

I think you want to use just `message.get_username()`
